In [127]:
import pandas as pd
import numpy as np

dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [128]:
X=dataset.iloc[:,2:3].values
#X=X.reshape(-1,1)
print(X)

y=dataset.iloc[:,4]
print(y)

[[19]
 [35]
 [26]
 [27]
 [19]
 [27]
 [27]
 [32]
 [25]
 [35]
 [26]
 [26]
 [20]
 [32]
 [18]
 [29]
 [47]
 [45]
 [46]
 [48]
 [45]
 [47]
 [48]
 [45]
 [46]
 [47]
 [49]
 [47]
 [29]
 [31]
 [31]
 [27]
 [21]
 [28]
 [27]
 [35]
 [33]
 [30]
 [26]
 [27]
 [27]
 [33]
 [35]
 [30]
 [28]
 [23]
 [25]
 [27]
 [30]
 [31]
 [24]
 [18]
 [29]
 [35]
 [27]
 [24]
 [23]
 [28]
 [22]
 [32]
 [27]
 [25]
 [23]
 [32]
 [59]
 [24]
 [24]
 [23]
 [22]
 [31]
 [25]
 [24]
 [20]
 [33]
 [32]
 [34]
 [18]
 [22]
 [28]
 [26]
 [30]
 [39]
 [20]
 [35]
 [30]
 [31]
 [24]
 [28]
 [26]
 [35]
 [22]
 [30]
 [26]
 [29]
 [29]
 [35]
 [35]
 [28]
 [35]
 [28]
 [27]
 [28]
 [32]
 [33]
 [19]
 [21]
 [26]
 [27]
 [26]
 [38]
 [39]
 [37]
 [38]
 [37]
 [42]
 [40]
 [35]
 [36]
 [40]
 [41]
 [36]
 [37]
 [40]
 [35]
 [41]
 [39]
 [42]
 [26]
 [30]
 [26]
 [31]
 [33]
 [30]
 [21]
 [28]
 [23]
 [20]
 [30]
 [28]
 [19]
 [19]
 [18]
 [35]
 [30]
 [34]
 [24]
 [27]
 [41]
 [29]
 [20]
 [26]
 [41]
 [31]
 [36]
 [40]
 [31]
 [46]
 [29]
 [26]
 [32]
 [32]
 [25]
 [37]
 [35]
 [33]
 [18]
 [22]
 [35]
 [29]
 [29]
 [21]
 [34]
 [26]
 [34]
 [34]
 [23]
 [35]
 [25]
 [24]
 [31]
 [26]
 [31]
 [32]
 [33]
 [33]
 [31]
 [20]
 [33]
 [35]
 [28]
 [24]
 [19]
 [29]
 [19]
 [28]
 [34]
 [30]
 [20]
 [26]
 [35]
 [35]
 [49]
 [39]
 [41]
 [58]
 [47]
 [55]
 [52]
 [40]
 [46]
 [48]
 [52]
 [59]
 [35]
 [47]
 [60]
 [49]
 [40]
 [46]
 [59]
 [41]
 [35]
 [37]
 [60]
 [35]
 [37]
 [36]
 [56]
 [40]
 [42]
 [35]
 [39]
 [40]
 [49]
 [38]
 [46]
 [40]
 [37]
 [46]
 [53]
 [42]
 [38]
 [50]
 [56]
 [41]
 [51]
 [35]
 [57]
 [41]
 [35]
 [44]
 [37]
 [48]
 [37]
 [50]
 [52]
 [41]
 [40]
 [58]
 [45]
 [35]
 [36]
 [55]
 [35]
 [48]
 [42]
 [40]
 [37]
 [47]
 [40]
 [43]
 [59]
 [60]
 [39]
 [57]
 [57]
 [38]
 [49]
 [52]
 [50]
 [59]
 [35]
 [37]
 [52]
 [48]
 [37]
 [37]
 [48]
 [41]
 [37]
 [39]
 [49]
 [55]
 [37]
 [35]
 [36]
 [42]
 [43]
 [45]
 [46]
 [58]
 [48]
 [37]
 [37]
 [40]
 [42]
 [51]
 [47]
 [36]
 [38]
 [42]
 [39]
 [38]
 [49]
 [39]
 [39]
 [54]
 [35]
 [45]
 [36]
 [52]
 [53]
 [41]
 [48]
 [48]
 [41]
 [41]
 [42]
 [36]
 [47]
 [38]
 [48]
 [42]
 [40]
 [57]
 [36]
 [58]
 [35]
 [38]
 [39]
 [53]
 [35]
 [38]
 [47]
 [47]
 [41]
 [53]
 [54]
 [39]
 [38]
 [38]
 [37]
 [42]
 [37]
 [36]
 [60]
 [54]
 [41]
 [40]
 [42]
 [43]
 [53]
 [47]
 [42]
 [42]
 [59]
 [58]
 [46]
 [38]
 [54]
 [60]
 [60]
 [39]
 [59]
 [37]
 [46]
 [46]
 [42]
 [41]
 [58]
 [42]
 [48]
 [44]
 [49]
 [57]
 [56]
 [49]
 [39]
 [47]
 [48]
 [48]
 [47]
 [45]
 [60]
 [39]
 [46]
 [51]
 [50]
 [36]
 [49]]
0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [129]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(X_train)

[[37]
 [29]
 [39]
 [26]
 [35]
 [45]
 [46]
 [32]
 [47]
 [50]
 [28]
 [45]
 [20]
 [46]
 [28]
 [31]
 [43]
 [23]
 [32]
 [24]
 [60]
 [38]
 [47]
 [47]
 [35]
 [58]
 [21]
 [48]
 [26]
 [47]
 [46]
 [50]
 [53]
 [42]
 [47]
 [34]
 [46]
 [37]
 [46]
 [19]
 [59]
 [48]
 [18]
 [34]
 [37]
 [55]
 [29]
 [35]
 [52]
 [22]
 [40]
 [35]
 [48]
 [42]
 [24]
 [44]
 [27]
 [40]
 [40]
 [27]
 [48]
 [52]
 [31]
 [52]
 [39]
 [19]
 [41]
 [59]
 [31]
 [35]
 [42]
 [32]
 [47]
 [29]
 [42]
 [33]
 [49]
 [27]
 [35]
 [30]
 [53]
 [49]
 [42]
 [35]
 [48]
 [39]
 [29]
 [35]
 [33]
 [27]
 [33]
 [35]
 [36]
 [24]
 [40]
 [34]
 [27]
 [29]
 [35]
 [37]
 [42]
 [35]
 [25]
 [36]
 [30]
 [37]
 [46]
 [28]
 [60]
 [48]
 [19]
 [46]
 [36]
 [18]
 [22]
 [41]
 [20]
 [33]
 [45]
 [32]
 [31]
 [35]
 [24]
 [54]
 [56]
 [40]
 [27]
 [56]
 [49]
 [32]
 [55]
 [30]
 [58]
 [48]
 [22]
 [28]
 [25]
 [29]
 [47]
 [59]
 [44]
 [36]
 [58]
 [51]
 [41]
 [25]
 [41]
 [58]
 [39]
 [59]
 [21]
 [19]
 [38]
 [23]
 [40]
 [47]
 [35]
 [21]
 [46]
 [19]
 [31]
 [38]
 [28]
 [32]
 [42]
 [20]
 [39]
 [36]
 [35]
 [42]
 [39]
 [30]
 [40]
 [23]
 [52]
 [51]
 [49]
 [36]
 [34]
 [41]
 [46]
 [37]
 [31]
 [52]
 [25]
 [40]
 [22]
 [21]
 [29]
 [28]
 [35]
 [35]
 [60]
 [26]
 [27]
 [37]
 [33]
 [47]
 [34]
 [45]
 [30]
 [23]
 [37]
 [47]
 [30]
 [48]
 [26]
 [37]
 [20]
 [38]
 [26]
 [54]
 [45]
 [48]
 [35]
 [47]
 [60]
 [54]
 [38]
 [31]
 [35]
 [35]
 [48]
 [58]
 [32]
 [30]
 [57]
 [35]
 [31]
 [26]
 [45]
 [41]
 [25]
 [41]
 [35]
 [42]
 [58]
 [37]
 [26]
 [35]
 [37]
 [40]
 [35]
 [41]
 [49]
 [30]
 [37]
 [31]
 [18]
 [31]
 [59]
 [35]
 [35]
 [40]
 [26]
 [42]
 [35]
 [36]
 [53]
 [46]
 [49]
 [36]
 [54]
 [24]
 [50]
 [39]
 [27]
 [31]
 [40]
 [37]
 [40]
 [26]
 [46]
 [48]
 [36]
 [28]
 [41]
 [38]
 [36]
 [45]
 [30]
 [49]
 [47]
 [37]
 [27]
 [24]
 [26]
 [22]
 [39]
 [37]
 [39]
 [29]
 [43]
 [49]
 [48]
 [47]
 [57]
 [36]
 [32]
 [27]
 [39]
 [19]
 [41]
 [38]
 [32]
 [60]
 [42]
 [26]
 [29]
 [40]
 [20]
 [48]
 [39]
 [46]
 [37]
 [42]
 [30]
 [60]
 [26]
 [38]]

In [130]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train.reshape(-1,1),y_train)

from sklearn.ensemble import RandomForestClassifier
randomClassifier=RandomForestClassifier(n_estimators=200,criterion='entropy',n_jobs=32)
randomClassifier.fit(X_train.reshape(-1,1),y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200, n_jobs=32)

In [131]:
y_pred=classifier.predict(X_test.reshape(-1,1))
y_predRandom=randomClassifier.predict(X_test.reshape(-1,1))
print(y_pred)
print(y_predRandom)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0
 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0
 0 0 0 0 0 1]

In [132]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

cmm=confusion_matrix(y_test,y_predRandom)
print(cmm)

[[52  3]
 [10 15]]
[[52  3]
 [10 15]]

In [133]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
print(acc)

acc1=accuracy_score(y_test,y_predRandom)
print(acc1)

0.8375
0.8375